### ISSUE TITLE
Require the FMC board for testing

### ISSUE THREAD

**Issue by yaobaishen** [daveshah1/CSI2Rx#1]
Hello, I am studying how to connect a MIPI camera to my xilinx ZYNQ7020 board, and find your repository, it's awesome.
As I only have a ZYNQ development board, which I buy from web seller, it doesn't have MIPI CSI-2 interface, so I am looking for a inter-connect board, just as your FMC board, so that I could buy a OV13850 module from web seller and have a try.
I mostly work as a software engineer so the electrical design is too difficult for me, from the README I read that you have a new FMC board on the road, could you share the  material, such as the PCB layout, or where to buy it, so that I can set up the full system? thanks.

**Comment by daveshah1** [comment]
In the end I made a combined FMC board for both DSI and CSI testing so it didn't end up in this repo, the board designs are here: [DSITx](https://github.com/daveshah1/DSITx/tree/master/hardware/fmc-v1.2).
I'll add a link in this repo too.
